const ELEMENT_IDS = [
  'paddingPercent',
  'paddingValue',
  'title',
  'titleColor',
  'titleColorHex',
  'titleSize',
  'titleSizeValue',
  'titleWeight',
  'titleFontFamily',
  'titleLetterSpacing',
  'titleLineHeight',
  'subtitle',
  'subtitleColor',
  'subtitleColorHex',
  'subtitleOpacity',
  'subtitleOpacityValue',
  'subtitleSize',
  'subtitleSizeValue',
  'subtitleWeight',
  'subtitleFontFamily',
  'subtitleLetterSpacing',
  'subtitleLineHeight',
  'subtitleGap',
  'legal',
  'legalColor',
  'legalColorHex',
  'legalOpacity',
  'legalOpacityValue',
  'legalSize',
  'legalSizeValue',
  'legalWeight',
  'legalFontFamily',
  'legalLetterSpacing',
  'legalLineHeight',
  'legalAlign',
  'age',
  'ageSize',
  'ageSizeValue',
  'ageFontFamily',
  'ageGapPercent',
  'showLogo',
  'showSubtitle',
  'hideSubtitleOnWide',
  'showLegal',
  'showAge',
  'showKV',
  'logoSelect',
  'logoSize',
  'logoSizeValue',
  'logoPreview',
  'logoActions',
  'logoThumb',
  'kvPreview',
  'kvActions',
  'kvThumb',
  'kvUpload',
  'kvSelect',
  'kvBorderRadius',
  'kvBorderRadiusValue',
  'bgColor',
  'bgColorHex',
  'bgPreviewContainer',
  'bgPreviewImg',
  'bgPreviewPlaceholder',
  'bgUploadBtn',
  'bgReplaceBtn',
  'bgDeleteBtn',
  'bgUpload',
  'textGradientOpacity',
  'textGradientOpacityValue',
  'fontFamily',
  'previewCanvas',
  'previewSizeSelect',
  'previewCanvasNarrow',
  'previewCanvasWide',
  'previewCanvasSquare',
  'previewSizeSelectNarrow',
  'previewSizeSelectWide',
  'previewSizeSelectSquare',
  'presetSizesList',
  'sizesSummary',
  'namePrefix'
];

const dom = {};

export const cacheDom = () => {
  ELEMENT_IDS.forEach((id) => {
    dom[id] = document.getElementById(id);
  });
  return dom;
};

export const getDom = () => dom;


